package de.kp.works.connect.mqtt;
/*
 * Copyright (c) 2020 Dr. Krusche & Partner PartG. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 * 
 * @author Stefan Krusche, Dr. Krusche & Partner PartG
 * 
 */

import java.io.Serializable;
import java.util.stream.Stream;

import javax.annotation.Nullable;

import com.google.common.base.Strings;

import co.cask.cdap.api.annotation.Description;
import co.cask.cdap.api.annotation.Macro;
import de.kp.works.connect.BaseConfig;
import de.kp.works.connect.zeek.MessageFormat;

public class MqttConfig extends BaseConfig implements Serializable {

	private static final long serialVersionUID = 1193310212809609121L;

	private static final String USER_DESC = "The MQTT user name or equivalent, such as the identifier "
			+ "of an application registered with an IoT cloud service.";
	
	private static final String PASSWORD_DESC = "The MQTT password or equivalent, such as the application "
			+ "key generated by an IoT cloud service.";
	
	@Description("The address of the MQTT broker to connect to, including protocol and port.")
	@Macro
	public String mqttBroker;

	@Description("The comma-separated list of MQTT topics to listen to.")
	@Macro
	public String mqttTopics;

	/***** AUTHENTICATION *****/
	
	@Description("The MQTT authentication method. Supported values are 'basic', 'x509' and 'x509_pem'. Default is 'basic'.")
	@Macro
	public String mqttAuth;
	
	@Description(USER_DESC)
	@Macro
	@Nullable
	public String mqttUser;

	@Description(PASSWORD_DESC)
	@Macro
	@Nullable
	public String mqttPassword;

	@Override
	public void validate() {
		super.validate();

		String className = this.getClass().getName();
		
		if (Strings.isNullOrEmpty(mqttBroker)) {
			throw new IllegalArgumentException(
					String.format("[%s] The MQTT broker address must not be empty.", className));
		}

		if (Strings.isNullOrEmpty(mqttTopics)) {
			throw new IllegalArgumentException(
					String.format("[%s] The MQTT topics must not be empty.", className));
		}
		
		/* Validate quthentication */
		
		MqttAuth auth = getAuth();
		switch (auth) {
		case BASIC: {
			
			if (Strings.isNullOrEmpty(mqttUser)) {
				throw new IllegalArgumentException(
						String.format("[%s] The MQTT user name must not be empty.", className));
			}
			
			if (Strings.isNullOrEmpty(mqttPassword)) {
				throw new IllegalArgumentException(
						String.format("[%s] The MQTT password must not be empty.", className));
			}
			
			break;
		}
		case X509: {
			break;
		}
		case X509_PEM: {
			break;
		}
		}
		

	}
	
	public MqttAuth getAuth() {
		
		Class<MqttAuth> enumClazz = MqttAuth.class;

		return Stream.of(enumClazz.getEnumConstants())
				.filter(keyType -> keyType.getValue().equalsIgnoreCase(mqttAuth)).findAny()
				.orElseThrow(() -> new IllegalArgumentException(
						String.format("Unsupported value for authentication method: '%s'", mqttAuth)));

	}
	
	public String[] getTopics() {
		
		String[] tokens = mqttTopics.split(",");
		String[]topics = new String[tokens.length];
		
		for (int i = 0; i < tokens.length; i++) {
			topics[i] = tokens[i].trim();
		}
		
		return topics;
		
	}
}
